import Head from 'next/head'
import Image from 'next/image'
import { Share_Tech_Mono, Fira_Sans } from '@next/font/google'
import styles from '../styles/Home.module.scss'
import { TextField, Button } from '@mui/material'

const shareTechMono = Share_Tech_Mono({ subsets: ['latin'], weight: '400' })
const firaSans = Fira_Sans({ subsets: ['latin'], weight: '400'})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles['wrapper']}>
          <div className={styles['home-container']}>
            <div className={styles['greeting']}>
              <div className={styles['brand']}><p className={shareTechMono.className}>life_invader</p></div>
              <div className={styles['greeting-message']}>
                <p className={firaSans.className}>Connect with friends and the world around you at life_invader.</p>
              </div>
            </div>
            <div className={styles['login']}>
              <TextField label="Email" />
              <TextField label="Password" />
              <Button variant="contained" size='large'><b>Log In</b></Button>
              <div className={styles['forgot']}><p>Forgot Password?</p></div>
              <div className={styles['break']}></div>
              <div>
                <Button variant="contained" color="secondary" size='large'><b>Sign Up</b></Button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
